---
name: 'Yamllint GitHub Actions'
on:
  - push
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'device*/*.yaml'
          yamllint_strict: false
          yamllint_config_filepath: '.yamllint-config.yml'
          yamllint_comment: true
